workflows:
  flutter_ios_workflow:
    name: Flutter iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_BUILD_MODE: release
    scripts:
      - name: Install dependencies
        script: |
          cd ios_frontend
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          cd ios_frontend
          flutter build ipa --release --no-codesign
           - name: Create unsigned IPA
      - name: Build iOS IPA
        script: |
          mkdir -p build/ios/ipa
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ios/ipa
    artifacts:
      - build/ios/iphoneos/*.ipa
