workflows:
  flutter_ios_workflow:
    name: Flutter iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_BUILD_MODE: release
    scripts:
      - name: Install dependencies
        script: |
          cd ios_frontend
          flutter pub get
          pod install
          cd ..
      - name: Build unsigned iOS app
        script: |
          cd ios_frontend
          flutter build ios --release --no-codesign
          if [ -d "build/ios/iphoneos/Runner.app" ]; then
            echo "Runner.app found, creating IPA..."
            mkdir -p build/ios/ipa/Payload
            cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
            cd build/ios/ipa
            zip -r Runner.ipa Payload
            cd ../../../
          else
            echo "Error: Runner.app not found!"
            exit 1
          fi
      - name: List IPA
        script: |
          echo "=== Listing iOS IPA directory ==="
          ls -R ios_frontend/build/ios/ipa
    artifacts:
      - ios_frontend/build/ios/ipa/Runner.ipa