workflows:
  flutter_ios_workflow:
    name: Flutter iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_BUILD_MODE: release
    scripts:
      - name: Install dependencies
        script: |
          cd ios_frontend
          flutter pub get
          pod install
          cd ..
      - name: Build iOS app
        script: |
          cd ios_frontend
          flutter build ipa --release
          echo "=== Listing iOS build output directories ==="
          ls -R build/ios
          echo "=== Listing iOS IPA directory ==="
          ls -R build/ios/ipa || true
          cd ..
    artifacts:
      - ios_frontend/build/ios/ipa/*.ipa